// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA2dDue5EPJywQU13kxIdaR-AgAEU-8A8M',
    appId: '1:244215310951:web:056581c3869b261d7842c2',
    messagingSenderId: '244215310951',
    projectId: 'employees-app-b21bf',
    authDomain: 'employees-app-b21bf.firebaseapp.com',
    storageBucket: 'employees-app-b21bf.appspot.com',
    measurementId: 'G-VZP3LNHCSS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBYq5jNe1ehzQ61fs4wsOPLs5vKDgSt7QY',
    appId: '1:244215310951:android:804baa496ed9b6a17842c2',
    messagingSenderId: '244215310951',
    projectId: 'employees-app-b21bf',
    storageBucket: 'employees-app-b21bf.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD54YDJJXSYJqDIBKTeIe-I6vL-D-0qKzo',
    appId: '1:244215310951:ios:e322dc5c1b0863ab7842c2',
    messagingSenderId: '244215310951',
    projectId: 'employees-app-b21bf',
    storageBucket: 'employees-app-b21bf.appspot.com',
    iosBundleId: 'com.example.employeesApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD54YDJJXSYJqDIBKTeIe-I6vL-D-0qKzo',
    appId: '1:244215310951:ios:e322dc5c1b0863ab7842c2',
    messagingSenderId: '244215310951',
    projectId: 'employees-app-b21bf',
    storageBucket: 'employees-app-b21bf.appspot.com',
    iosBundleId: 'com.example.employeesApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA2dDue5EPJywQU13kxIdaR-AgAEU-8A8M',
    appId: '1:244215310951:web:9050879bf2633fbd7842c2',
    messagingSenderId: '244215310951',
    projectId: 'employees-app-b21bf',
    authDomain: 'employees-app-b21bf.firebaseapp.com',
    storageBucket: 'employees-app-b21bf.appspot.com',
    measurementId: 'G-3DH8RXJ1LD',
  );
}
